name: cyan_flutter
description: Cyan - P2P Collaboration Platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  zxing2: ^0.2.0  
  flutter_riverpod: ^2.4.9
  ffi: ^2.1.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  google_sign_in: ^6.2.1
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  qr_flutter: ^4.1.0
  uuid: ^4.3.3
  intl: ^0.19.0
  collection: ^1.18.0
  equatable: ^2.0.5
  universal_platform: ^1.0.0+1
  flutter_code_editor: ^0.3.0
  highlight: ^0.7.0
  desktop_drop: ^0.4.4
  file_picker: ^6.1.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
